[package]
name = "libusb-demo"
version = "0.1.0"
edition = "2018"
build = "src/build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb = "0.3.0"

[build-dependencies]
pkg-config = "0.3.2"
